# Generated by Django 2.1.7 on 2020-10-16 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('Answervoters', models.ManyToManyField(related_name='Answervotes', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contest_register_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_teamname', models.CharField(default=1, max_length=200)),
                ('contest_teamcontact', models.IntegerField(blank=True, null=True)),
                ('contest_adminname', models.CharField(default=1, max_length=200)),
                ('contest_team_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contestteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamcontact', models.IntegerField(blank=True, null=True)),
                ('contactname', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.URLField()),
                ('highlightsvoters', models.ManyToManyField(related_name='highlightsvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_goals', models.IntegerField()),
                ('team_b_goals', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('winner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('playerpasscode', models.IntegerField(blank=True, default='0000', null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('facebookurl', models.CharField(blank=True, max_length=100, null=True)),
                ('instaurl', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, default='unknown', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='hey! i am a battle soccer player', max_length=200, null=True)),
                ('pic', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='woman-playing.png', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(blank=True, max_length=10, null=True)),
                ('teamname', models.CharField(blank=True, default='Team name', max_length=100, null=True)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='soccer_logo.jpeg', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='')),
                ('coverpic', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='soccer.jpeg', force_format=None, keep_meta=True, null=True, quality=100, size=[800, 350], upload_to='')),
                ('teamquotes', models.CharField(blank=True, default='hey!I am ready for the battle', max_length=20000, null=True)),
                ('teamcontact', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teamrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(default=1, max_length=200)),
                ('teamgoals', models.IntegerField()),
                ('matchs_played', models.IntegerField()),
                ('match_won', models.IntegerField()),
                ('match_lost', models.IntegerField()),
                ('teamown', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateTimeField(auto_now_add=True)),
                ('tour_name', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='teamrank',
            name='tournament_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='voters',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='belongs', to='app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='app.tournament'),
        ),
        migrations.AddField(
            model_name='highlights',
            name='teamname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.team'),
        ),
        migrations.AddField(
            model_name='highlights',
            name='tournament_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tourhighlight', to='app.tournament'),
        ),
        migrations.AddField(
            model_name='contestteam',
            name='teamown',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.AddField(
            model_name='answer',
            name='highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.highlights'),
        ),
    ]
