# Generated by Django 2.1.7 on 2020-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201016_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamcity',
            field=models.CharField(blank=True, default='unknown', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tour_city',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
