# Generated by Django 2.1.7 on 2020-10-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201020_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchvideos', models.URLField()),
                ('team_a', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='app.team')),
                ('team_b', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='app.team')),
                ('tournament_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tourmatchvideos', to='app.tournament')),
            ],
        ),
    ]
