# Generated by Django 2.1.7 on 2020-10-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201024_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tour_defender',
            new_name='tour_fairplay',
        ),
    ]
