# Generated by Django 2.1.7 on 2020-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201024_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='unk12nown', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tour_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
