# Generated by Django 2.1.7 on 2020-10-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201028_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='unknown', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tour_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
