# Generated by Django 2.1.7 on 2020-10-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201028_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tour_date',
        ),
    ]
