# Generated by Django 2.1.7 on 2020-10-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_tournament_tour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tour_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
