# Generated by Django 2.1.7 on 2020-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tournament_tour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tour_price',
            field=models.IntegerField(default=1, max_length=200),
        ),
    ]
